### ISSUE TITLE
Wrong unit reported in rotation plots(?)

### ISSUE THREAD

**Issue by tobiscode** [kmaterna/Strain_2D#43]
Hi,

while coding up the simple, Python-based VISR method I realized that the rotation plots that presumably output [rad/ka] actually output [rad/Ga]. Looking at the [comparison figure](https://github.com/kmaterna/Strain_2D/blob/528b2792b520d87fe7bc18f8fecb5ff8c60614ea/example/Display_output/output_rows.png), it suggests that at the coast, the patches there would complete almost 50 complete turns around themselves in 1000 years - that seems a bit unrealistic. Digging deeper I realized that the unit conversion in `delaunay_flat` for the rotation is wrong, since the assumed units of the output of the gradient matrix are wrong.

Specifically, in [this section](https://github.com/kmaterna/Strain_2D/blob/528b2792b520d87fe7bc18f8fecb5ff8c60614ea/Strain_Tools/strain/models/strain_delaunay_flat.py#L138-L142):
```python
        # Convert to nanostrain
        exx.append(np.multiply(exx_triangle, 1000))
        exy.append(np.multiply(exy_triangle, 1000))
        eyy.append(np.multiply(eyy_triangle, 1000))
        rot.append(abs(np.multiply(rotation_triangle, 1000)))
```
the factor 1000 converts the strain quantities from their original 10^-6 (because the input was fed with millimeters and not meters) to 10^-9 (the desired nanostrain). However, `rotation_triangle`, which has the same scaling, should then be _divided_ by 1000, not multiplied. I only stumbled across this because I had to multiply my simple VISR rotation rate method output to make it match the example plots.

And then I'm assuming since all the units have to be the same to make the same outputs, all the other methods scaled themselves to match the output? For example, the `loc_avg_grad` method has the line `rot[j, i] = omega * 1e9`, which should only multiply by 1000 to go from [rad/a] to [rad/ka]. Although I of course don't know which method was the first to get this unit.

Or am I understanding something completely wrong?..

Cheers

**Comment by kmaterna** [comment]
@tobiscode I believe you're right!  I see a lot of 1e-9 in the output parts of multiple strain modules. It's entirely possible that one method started with the wrong unit conversion and the others all just matched.  I'm going to build a new test that starts with the known rotation of three points around an Euler Pole, and tests that each strain method gets the right answer in the right units... then fix the readme... then I'll resolve the issue.

**Comment by kmaterna** [comment]
I can confirm by putting in a synthetic velocity grid with a known rotation (1°/Ma = 17.45 rad/Ga), that the units reported are in rad/Ga.  

I also found a bunch of sign conventions were different between the different methods! For example: 
```
Delaunay: 17.456873296060625 rad/Ga
Delaunay_Flat: 10.287381725277475 rad/Ga
visr: -10.3 rad/Ga
gpsgridder: 11.616745 rad/Ga
loc_avg_grad: -10.298336061484274 rad/Ga
geostats: -9.683197292479532 rad/Ga
```

I think the magnitude differences observed are because of spherical geometry.  I input 17.45.  This rotation is far from the Euler Pole, so the spherical aspect matters. Delaunay (the spherical version) might be the only one that truly operates on a sphere.  I think?  

So, I made a couple changes: flipping signs of both Delaunays, and removing a rogue absolute-value from gpsgridder!  I also updated the README and plots to say that all rotations are in rad/Ga and positive is clockwise.

**Comment by kmaterna** [comment]
Commit here: https://github.com/kmaterna/Strain_2D/commit/97fa7ae3fd4052d140f035d9d12f12406fc0195e

Thank you for noticing!  Any other changes you noticed while we're on it?

**Comment by tobiscode** [comment]
Thanks for testing and confirming this! And I'm not sure about the other approaches, but at least my VISR is on a flattened earth, yes.

One small issue still maybe: I believe at least in the `delaunay_flat`, the reported rotation is actually an absolute value, so just changing the sign wouldn't solve the issue of the direction, see the [code snippet](https://github.com/kmaterna/Strain_2D/blob/528b2792b520d87fe7bc18f8fecb5ff8c60614ea/Strain_Tools/strain/models/strain_delaunay_flat.py#L138-L142) in the first post. Is this correct?

**Comment by kmaterna** [comment]
Good point.  I fixed that issue in delaunay_flat, and made the sign convention match. 
I also had to do some fixing in delaunay spherical, since the original authors had only reported the magnitude of the rotation vector. I added a little adjustment for whether the radial part of that vector points up or down. 
Now both delaunays pass the tests for both clockwise and counterclockwise rotations. 

https://github.com/kmaterna/Strain_2D/blob/5685b8f5f05719cb1b068f59ee1a4d32a9c8e419/Strain_Tools/strain/models/strain_delaunay.py#L348 
Fix: 
https://github.com/kmaterna/Strain_2D/blob/5685b8f5f05719cb1b068f59ee1a4d32a9c8e419/Strain_Tools/strain/models/strain_delaunay.py#L383

**Comment by tobiscode** [comment]
Awesome! and `gpsgridder` also outputs the negative rotation rate? If so, then I think it's fine to close this issue. I'll update my pull request with a commit that also adopts that rotation sign convention.
